In [1]:
import numpy as np

In [39]:
arry3 =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
arry3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arry3[1]

array([4, 5, 6])

In [42]:
arry3[1,2]

6

In [43]:
arry3[:1]

array([[1, 2, 3]])

In [44]:
arry3[:2,1:]

array([[2, 3],
       [5, 6]])

In [45]:
arry3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr_len = arry3.shape[1]

In [52]:
arr_len

3

In [57]:
for i in range(arr_len):
    arry3[i] = 9

In [58]:
arry3

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [63]:
np.arange(10,1,1)

array([], dtype=int32)