In [64]:
import numpy as np

In [65]:
arry = np.arange(50).reshape(10,5)

In [66]:
arry

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [67]:
arry.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [68]:
arry.dot(arry.T)

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])

In [70]:
arry.swapaxes(0,1)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [71]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [72]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
b = np.array([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]])

In [75]:
b


array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [76]:
np.maximum(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.add(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
np.add(a,-b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])